 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  llava_depth_qa_instruct: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    vis_processor:
      train:
        name: alpro_video_train
        n_frms: 2
        image_size: 224
        min_scale: 0.9
        max_scale: 1.0
        full_video: True
      eval:
        name: alpro_video_eval
        n_frms: 2
        image_size: 224
        min_scale: 0.9
        max_scale: 1.0
        full_video: True
    
    text_processor:
      train:
        name: blip_instruction
        task: qa
        modality: video
      eval:
        name: blip_question
        
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/qa_train.json
          storage: path_to_your_data/process_llava150k/llava_instruct_50k_train_data.json
        val:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/qa_val.json
          storage: /path_to_your_data/SUNRGBD/SUN-RGBD_val.json
#        test:
#          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/qa_test.json
#          storage: /15324359926/Multimodal/datasets_multimodal/MSRVTT/annotations/qa_test.json
        # ans2label:
        #   url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/msrvtt/train_ans2label.json
        #   storage: /15324359926/Multimodal/datasets_multimodal/MSRVTT/annotations/qa_ans2label.json
      videos:
        storage: /path_to_your_data/data/coco/train2017
